[package]
name = "palworld-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
commander-rust = "1.2.1"
dialoguer = "0.11.0"
num_cpus = "1.14.0"
rand = "0.8"